### ISSUE TITLE
Upgrade ember-source

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-factfinder#599]

**Comment by chriswhong** [comment]
Upgrading to  3.3.0 breaks tests

**Comment by allthesignals** [comment]
Upgrading ember can be a process. I use ‘ember-cli-update’ for that.

**Comment by allthesignals** [comment]
Is there a branch I should be looking at? Just going to go off develop

**Comment by allthesignals** [comment]
List of changes:

- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/comparison-area-selector.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/data-table-row-change.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/data-table-row-current.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/data-table.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/layer-group.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/layer-menu-item.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/map-search.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/map-utility-box.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/profile-header.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/components/tab-dropdown.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/controllers/index.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/controllers/profile.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/controllers/profile/census.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/controllers/profile/demographic.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/controllers/profile/economic.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/controllers/profile/housing.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/controllers/profile/social.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/models/row.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/services/map-mouseover.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/services/registered-layers.js
- [ ] /Users/mgardner/labs-nyc-factfinder/app/services/selection.js


Need to change the import of `computed` to this:
```
import { computed } from '@ember/object';
```

Need to change from "old" to "classic":
```
  // old
  @computed('comparisonArea', 'options')
  selected(area, options) {
    return options
      .then(d => d.findBy('geoid', area))
      .then((selected) => {
        this.set('selection.comparisonLabel', selected.label);
        return selected;
      });
  },

  // classic
  selected: computed('comparisonArea', 'options', function() {
    const area = this.get('comparisonArea');
    const options = this.get('options');

    return options
      .then(d => d.findBy('geoid', area))
      .then((selected) => {
        this.set('selection.comparisonLabel', selected.label);
        return selected;
      });
  },
```

**Comment by allthesignals** [comment]
Thanks for the help on the above comment. 

I've got the app in a functional state. The Foundation Sites stuff does not import for some reason:

> Sass Syntax Error (SassCompiler) in 1/foundation-sites/foundation.scss:10:9
> 
> Error: Can't find stylesheet to import.
> @import '../_vendor/sassy-lists/stylesheets/helpers/missing-dependencies';
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   tmp/sass_compiler-input_base_path-ETa29LXg.tmp/1/foundation-sites/foundation.scss 10:9  @import
>   tmp/sass_compiler-input_base_path-ETa29LXg.tmp/0/app/styles/app.scss 27:9               root stylesheet
> 
> 
> Stack Trace and Error Report: /var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/error.dump.638d51a8697ad534001b3869f232e216.log

Maybe this will be fixed by implementing labs-ui? @andycochran. 

Also, I upgraded all the addons. Some had breaking changes. ember-tooltips has an upgrade doc to double check some functionality: https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md

I changed all the component names here to match what the new version uses. The only thing that might not work is specific options set on those components. 

Please watch for "cannot find xyz of undefined". This usually means something went wrong when we switched from stage 2 decorator syntax to classic computeds. 

Please work from the branch here: https://github.com/NYCPlanning/labs-factfinder/tree/599-upgrade-ember-2

**Comment by allthesignals** [comment]
Remaining issues:

 - [ ] Re-enable and fix `ember-cli-data-export`, which relies on outdated pre-module syntax. Main error is "cannot find module `ember`". 
 - [ ] Check that tooltips are working again. Because of the major version upgrade, our settings may not be working anymore.
 - [ ] Make sure test runner still works
 - [ ] Fix Foundation Sites. Currently I've removed those deps and commented out all of app.scss so that I could move on to things I know how to fix. Need @andycochran for this one.
 - [ ] Check drawing functionality
 - [ ] Merge with other changes
 - [ ] Re-enable "trackEvent", which was pushing to GA (it was a decorator and had to be disabled)
 - [ ] Does D3 still work?
 - [ ] QA in all computed properties that the initial `this.get('')` (first line of the computed) is really getting a property that exists.
 - [ ] Manual test map features
